export const KOPI_KENANGAN_PRODUCTS = [
  {
    "id": "kk_prod_201",
    "brand_id": "brand_kopi_kenangan",
    "name": "Kopi Kenangan Mantan",
    "image": "https://i.ibb.co.com/0yQbyxDQ/Frame-1410112838.png",
    "description": "Kopi Kenangan Mantan segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_202",
    "brand_id": "brand_kopi_kenangan",
    "name": "Spanish Latte",
    "image": "https://i.ibb.co.com/DHVVbdkX/Frame-1410112842.png",
    "description": "Spanish Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_203",
    "brand_id": "brand_kopi_kenangan",
    "name": "Butterscotch Aren Latte",
    "image": "https://i.ibb.co.com/BVvpZ7hR/Frame-1410112854.png",
    "description": "Butterscotch Aren Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_204",
    "brand_id": "brand_kopi_kenangan",
    "name": "Americano",
    "image": "https://i.ibb.co.com/Z6KK2CYy/Frame-1410112853.png",
    "description": "Americano segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_205",
    "brand_id": "brand_kopi_kenangan",
    "name": "Blueberry Americano",
    "image": "https://i.ibb.co.com/Z6KK2CYy/Frame-1410112853.png",
    "description": "Blueberry Americano segar dan nikmat khas Kopi Kenangan.",
    "price": 19000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_206",
    "brand_id": "brand_kopi_kenangan",
    "name": "Pistachio Aren Latte",
    "image": "https://i.ibb.co.com/8Hyvm5b/Frame-1410112862.png",
    "description": "Pistachio Aren Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_207",
    "brand_id": "brand_kopi_kenangan",
    "name": "Toffee Nut Latte",
    "image": "https://i.ibb.co.com/zVbBCRkY/Frame-1410112861.png",
    "description": "Toffee Nut Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_208",
    "brand_id": "brand_kopi_kenangan",
    "name": "OG Thai Tea",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "OG Thai Tea segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_209",
    "brand_id": "brand_kopi_kenangan",
    "name": "Babycino",
    "image": "https://i.ibb.co.com/XkSQgfyS/Frame-1410112886.png",
    "description": "Babycino segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_210",
    "brand_id": "brand_kopi_kenangan",
    "name": "Raspberry Hibiscus",
    "image": "https://i.ibb.co.com/99wF5vh5/Frame-1410112874.png",
    "description": "Raspberry Hibiscus segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_211",
    "brand_id": "brand_kopi_kenangan",
    "name": "Banana Americano",
    "image": "https://i.ibb.co.com/Z6KK2CYy/Frame-1410112853.png",
    "description": "Banana Americano segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_212",
    "brand_id": "brand_kopi_kenangan",
    "name": "Fresh Lemonade",
    "image": "https://i.ibb.co.com/FqHmjmM4/Frame-1410112870.png",
    "description": "Fresh Lemonade segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_213",
    "brand_id": "brand_kopi_kenangan",
    "name": "Lemon Black Tea",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Lemon Black Tea segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_214",
    "brand_id": "brand_kopi_kenangan",
    "name": "Choco Caramel",
    "image": "https://i.ibb.co.com/YFz0B2vk/Frame-1410112869.png",
    "description": "Choco Caramel segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_215",
    "brand_id": "brand_kopi_kenangan",
    "name": "Air Mineral (Pristine)",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Air Mineral (Pristine) segar dan nikmat khas Kopi Kenangan.",
    "price": 5000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 1
  },
  {
    "id": "kk_prod_1",
    "brand_id": "brand_kopi_kenangan",
    "name": "Latte",
    "image": "https://i.ibb.co.com/nMPfxRc3/Frame-1410112855.png",
    "description": "Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_2",
    "brand_id": "brand_kopi_kenangan",
    "name": "Americano",
    "image": "https://i.ibb.co.com/Z6KK2CYy/Frame-1410112853.png",
    "description": "Americano segar dan nikmat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_3",
    "brand_id": "brand_kopi_kenangan",
    "name": "Cappuccino",
    "image": "https://i.ibb.co.com/wZ6ySXyR/Frame-1410112852.png",
    "description": "Cappuccino segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_4",
    "brand_id": "brand_kopi_kenangan",
    "name": "Spanish Latte",
    "image": "https://i.ibb.co.com/DHVVbdkX/Frame-1410112842.png",
    "description": "Spanish Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_5",
    "brand_id": "brand_kopi_kenangan",
    "name": "Vanilla Latte",
    "image": "https://i.ibb.co.com/spKHQyYj/Frame-1410112841.png",
    "description": "Vanilla Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 17000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_6",
    "brand_id": "brand_kopi_kenangan",
    "name": "Hazelnut Latte",
    "image": "https://i.ibb.co.com/Fky0GJzH/Frame-1410112846.png",
    "description": "Hazelnut Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 17000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_7",
    "brand_id": "brand_kopi_kenangan",
    "name": "Caramel Latte",
    "image": "https://i.ibb.co.com/PvFsvH97/Frame-1410112847.png",
    "description": "Caramel Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 17000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_8",
    "brand_id": "brand_kopi_kenangan",
    "name": "Cafe Malt Latte",
    "image": "https://i.ibb.co.com/3yzHQLNQ/Frame-1410112848.png",
    "description": "Cafe Malt Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 15500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_9",
    "brand_id": "brand_kopi_kenangan",
    "name": "Caramel Macchiato",
    "image": "https://i.ibb.co.com/3YhzGVh0/Frame-1410112845.png",
    "description": "Caramel Macchiato segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_10",
    "brand_id": "brand_kopi_kenangan",
    "name": "Mocha Latte",
    "image": "https://i.ibb.co.com/0yQbyxDQ/Frame-1410112838.png",
    "description": "Mocha Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_11",
    "brand_id": "brand_kopi_kenangan",
    "name": "Kopi Susu Black Aren",
    "image": "https://i.ibb.co.com/0yQbyxDQ/Frame-1410112838.png",
    "description": "Kopi Susu Black Aren segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_12",
    "brand_id": "brand_kopi_kenangan",
    "name": "Toffee Nut Latte",
    "image": "https://i.ibb.co.com/zVbBCRkY/Frame-1410112861.png",
    "description": "Toffee Nut Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_13",
    "brand_id": "brand_kopi_kenangan",
    "name": "Toffee Nut Aren Latte",
    "image": "https://i.ibb.co.com/vC66ngqh/Frame-1410112859.png",
    "description": "Toffee Nut Aren Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_14",
    "brand_id": "brand_kopi_kenangan",
    "name": "Tiramisu Latte",
    "image": "https://i.ibb.co.com/6cXLXLqv/Frame-1410112860.png",
    "description": "Tiramisu Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 14000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_15",
    "brand_id": "brand_kopi_kenangan",
    "name": "Tiramisu Mocha Latte",
    "image": "https://i.ibb.co.com/KkFbMRd/Frame-1410112863.png",
    "description": "Tiramisu Mocha Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_16",
    "brand_id": "brand_kopi_kenangan",
    "name": "Butterscotch Sea Salt Latte",
    "image": "https://i.ibb.co.com/BVvpZ7hR/Frame-1410112854.png",
    "description": "Butterscotch Sea Salt Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_17",
    "brand_id": "brand_kopi_kenangan",
    "name": "Creamy Aren Latte",
    "image": "https://i.ibb.co.com/JRPdckcj/Frame-1410112856.png",
    "description": "Creamy Aren Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_18",
    "brand_id": "brand_kopi_kenangan",
    "name": "Pistachio Aren Latte",
    "image": "https://i.ibb.co.com/8Hyvm5b/Frame-1410112862.png",
    "description": "Pistachio Aren Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_19",
    "brand_id": "brand_kopi_kenangan",
    "name": "Matcha Espresso",
    "image": "https://i.ibb.co.com/yFq7sPD7/Frame-1410112839.png",
    "description": "Matcha Espresso segar dan nikmat khas Kopi Kenangan.",
    "price": 17000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_20",
    "brand_id": "brand_kopi_kenangan",
    "name": "Avocado Coffee",
    "image": "https://i.ibb.co.com/5PXyL5H/Frame-1410112843.png",
    "description": "Avocado Coffee segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_45",
    "brand_id": "brand_kopi_kenangan",
    "name": "Kopi Kenangan Mantan",
    "image": "https://i.ibb.co.com/0yQbyxDQ/Frame-1410112838.png",
    "description": "Kopi Kenangan Mantan segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_46",
    "brand_id": "brand_kopi_kenangan",
    "name": "Salted Caramel Macchiato",
    "image": "https://i.ibb.co.com/3YhzGVh0/Frame-1410112845.png",
    "description": "Salted Caramel Macchiato segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_21",
    "brand_id": "brand_kopi_kenangan",
    "name": "Matcha Latte",
    "image": "https://i.ibb.co.com/BvcbFLH/Frame-1410112878.png",
    "description": "Matcha Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_22",
    "brand_id": "brand_kopi_kenangan",
    "name": "Oatside Matcha Latte",
    "image": "https://i.ibb.co.com/FLz7TCqr/Frame-1410112866.png",
    "description": "Oatside Matcha Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Oatside",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_23",
    "brand_id": "brand_kopi_kenangan",
    "name": "Dutch Chocolate",
    "image": "https://i.ibb.co.com/WNXkfp4Q/Frame-1410112840.png",
    "description": "Dutch Chocolate segar dan nikmat khas Kopi Kenangan.",
    "price": 17000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_24",
    "brand_id": "brand_kopi_kenangan",
    "name": "Hazelnut Dutch Choco",
    "image": "https://i.ibb.co.com/zT1QrgSS/Frame-1410112868.png",
    "description": "Hazelnut Dutch Choco segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_25",
    "brand_id": "brand_kopi_kenangan",
    "name": "Choco Caramel",
    "image": "https://i.ibb.co.com/YFz0B2vk/Frame-1410112869.png",
    "description": "Choco Caramel segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_26",
    "brand_id": "brand_kopi_kenangan",
    "name": "Mocha Caramel",
    "image": "https://i.ibb.co.com/YFz0B2vk/Frame-1410112869.png",
    "description": "Mocha Caramel segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_27",
    "brand_id": "brand_kopi_kenangan",
    "name": "Avocado Milk",
    "image": "https://i.ibb.co.com/4ZvNd6WQ/Frame-1410112867.png",
    "description": "Avocado Milk segar dan nikmat khas Kopi Kenangan.",
    "price": 16000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_28",
    "brand_id": "brand_kopi_kenangan",
    "name": "Avocado Caramel",
    "image": "https://i.ibb.co.com/8CwcZdH/Frame-1410112871.png",
    "description": "Avocado Caramel segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_29",
    "brand_id": "brand_kopi_kenangan",
    "name": "Raspberry Hibiscus",
    "image": "https://i.ibb.co.com/99wF5vh5/Frame-1410112874.png",
    "description": "Raspberry Hibiscus segar dan nikmat khas Kopi Kenangan.",
    "price": 14000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_30",
    "brand_id": "brand_kopi_kenangan",
    "name": "Hazelnut Choco Milk Tea",
    "image": "https://i.ibb.co.com/qY3c3bPT/Frame-1410112872.png",
    "description": "Hazelnut Choco Milk Tea segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_32",
    "brand_id": "brand_kopi_kenangan",
    "name": "Fresh Lemonade",
    "image": "https://i.ibb.co.com/FqHmjmM4/Frame-1410112870.png",
    "description": "Fresh Lemonade segar dan nikmat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_33",
    "brand_id": "brand_kopi_kenangan",
    "name": "Thai Tea",
    "image": "https://i.ibb.co.com/Zp4Nwdk2/Frame-1410112877.png",
    "description": "Thai Tea segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_34",
    "brand_id": "brand_kopi_kenangan",
    "name": "Milk Oreo Crumble",
    "image": "https://i.ibb.co.com/gMBR7mX6/Frame-1410112875.png",
    "description": "Milk Oreo Crumble segar dan nikmat khas Kopi Kenangan.",
    "price": 17000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_35",
    "brand_id": "brand_kopi_kenangan",
    "name": "Toffee Nut Choco Macchiato",
    "image": "https://i.ibb.co.com/TM0ykDKY/Frame-1410112884.png",
    "description": "Toffee Nut Choco Macchiato segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_36",
    "brand_id": "brand_kopi_kenangan",
    "name": "Susu Grass Jelly",
    "image": "https://i.ibb.co.com/nMKJY7gj/Frame-1410112876.png",
    "description": "Susu Grass Jelly segar dan nikmat khas Kopi Kenangan.",
    "price": 16000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_37",
    "brand_id": "brand_kopi_kenangan",
    "name": "Babyccino",
    "image": "https://i.ibb.co.com/XkSQgfyS/Frame-1410112886.png",
    "description": "Babyccino segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_47",
    "brand_id": "brand_kopi_kenangan",
    "name": "Air Mineral",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Air Mineral segar dan nikmat khas Kopi Kenangan.",
    "price": 7500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_48",
    "brand_id": "brand_kopi_kenangan",
    "name": "Caramel Dutch Choco",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Caramel Dutch Choco segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_49",
    "brand_id": "brand_kopi_kenangan",
    "name": "Lemon Black Tea",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Lemon Black Tea segar dan nikmat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_50",
    "brand_id": "brand_kopi_kenangan",
    "name": "Kenangan Milk Tea",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Kenangan Milk Tea segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_51",
    "brand_id": "brand_kopi_kenangan",
    "name": "Milo Dinosaurus",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Milo Dinosaurus segar dan nikmat khas Kopi Kenangan.",
    "price": 15500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_52",
    "brand_id": "brand_kopi_kenangan",
    "name": "Oreo Shake",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Oreo Shake segar dan nikmat khas Kopi Kenangan.",
    "price": 17000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_53",
    "brand_id": "brand_kopi_kenangan",
    "name": "Dubai Pistachio Chocolate",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Dubai Pistachio Chocolate segar dan nikmat khas Kopi Kenangan.",
    "price": 17500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_54",
    "brand_id": "brand_kopi_kenangan",
    "name": "Butterscotch Sea Salt",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Butterscotch Sea Salt segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":false,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_55",
    "brand_id": "brand_kopi_kenangan",
    "name": "OG Thai Tea",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "OG Thai Tea segar dan nikmat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_56",
    "brand_id": "brand_kopi_kenangan",
    "name": "Thai Tea Loaded",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Thai Tea Loaded segar dan nikmat khas Kopi Kenangan.",
    "price": 17500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":false,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_57",
    "brand_id": "brand_kopi_kenangan",
    "name": "Thai Tea Aren",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Thai Tea Aren segar dan nikmat khas Kopi Kenangan.",
    "price": 16000,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":false,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_58",
    "brand_id": "brand_kopi_kenangan",
    "name": "Thai Tea Coffee",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Thai Tea Coffee segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Non-Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":false,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_60",
    "brand_id": "brand_kopi_kenangan",
    "name": "Oatside Kopi Kenangan",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Oatside Kopi Kenangan segar dan nikmat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Oatside",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_61",
    "brand_id": "brand_kopi_kenangan",
    "name": "Oatside Latte",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Oatside Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Oatside",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_62",
    "brand_id": "brand_kopi_kenangan",
    "name": "OG Aren Milky Speculoos",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "OG Aren Milky Speculoos segar dan nikmat khas Kopi Kenangan.",
    "price": 15500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_63",
    "brand_id": "brand_kopi_kenangan",
    "name": "OG Aren Speculoos Latte",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "OG Aren Speculoos Latte segar dan nikmat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_64",
    "brand_id": "brand_kopi_kenangan",
    "name": "Dua Shot OG Aren",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Dua Shot OG Aren segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Kopi",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":true,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_65",
    "brand_id": "brand_kopi_kenangan",
    "name": "Pistachio Frappe",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Pistachio Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 20000,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_66",
    "brand_id": "brand_kopi_kenangan",
    "name": "Butterscotch Kenangan Frappe",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Butterscotch Kenangan Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 19000,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_38",
    "brand_id": "brand_kopi_kenangan",
    "name": "Tiramisu Frappe",
    "image": "https://i.ibb.co.com/vxfBjc1m/Frame-1410112873.png",
    "description": "Tiramisu Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_39",
    "brand_id": "brand_kopi_kenangan",
    "name": "Matcha Kenangan Frappe",
    "image": "https://i.ibb.co.com/0RPp1jCJ/Frame-1410112888.png",
    "description": "Matcha Kenangan Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 20000,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_40",
    "brand_id": "brand_kopi_kenangan",
    "name": "Dutch Choco Kenangan Frappe",
    "image": "https://i.ibb.co.com/PsZWwjjR/Frame-1410112882.png",
    "description": "Dutch Choco Kenangan Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 18500,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_41",
    "brand_id": "brand_kopi_kenangan",
    "name": "Kopi Kenangan Mantan Frappe",
    "image": "https://i.ibb.co.com/9HNKVYM4/Frame-1410112881.png",
    "description": "Kopi Kenangan Mantan Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 17500,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":true,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_42",
    "brand_id": "brand_kopi_kenangan",
    "name": "Vanilla Kenangan Frappe",
    "image": "https://i.ibb.co.com/nqWWZDnP/Frame-1410112887.png",
    "description": "Vanilla Kenangan Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 16500,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_43",
    "brand_id": "brand_kopi_kenangan",
    "name": "Choco Caramel Frappe",
    "image": "https://i.ibb.co.com/vxfBjc1m/Frame-1410112873.png",
    "description": "Choco Caramel Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_44",
    "brand_id": "brand_kopi_kenangan",
    "name": "Mocha Caramel Frappe",
    "image": "https://i.ibb.co.com/vxfBjc1m/Frame-1410112873.png",
    "description": "Mocha Caramel Frappe segar dan nikmat khas Kopi Kenangan.",
    "price": 18000,
    "category": "Frappe",
    "availability": "ON",
    "customization_json": "{\"has_suhu\":false,\"has_ukuran\":true,\"has_es\":true,\"has_gula\":true,\"has_beans\":false,\"has_syrup\":true,\"has_topping\":true}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_140",
    "brand_id": "brand_kopi_kenangan",
    "name": "Thai Chicken Spaghetti",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Thai Chicken Spaghetti lezat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_100",
    "brand_id": "brand_kopi_kenangan",
    "name": "Croissant Abon",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Croissant Abon lezat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_101",
    "brand_id": "brand_kopi_kenangan",
    "name": "Pasta Mentai",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Pasta Mentai lezat khas Kopi Kenangan.",
    "price": 16000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_102",
    "brand_id": "brand_kopi_kenangan",
    "name": "Salt Bread Beef & Cheese",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Salt Bread Beef & Cheese lezat khas Kopi Kenangan.",
    "price": 11000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_103",
    "brand_id": "brand_kopi_kenangan",
    "name": "Bolu Marble Chocolate",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Bolu Marble Chocolate lezat khas Kopi Kenangan.",
    "price": 11000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_104",
    "brand_id": "brand_kopi_kenangan",
    "name": "Pasta Indoghetti",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Pasta Indoghetti lezat khas Kopi Kenangan.",
    "price": 15000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_105",
    "brand_id": "brand_kopi_kenangan",
    "name": "Donut Almond",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Donut Almond lezat khas Kopi Kenangan.",
    "price": 10500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_106",
    "brand_id": "brand_kopi_kenangan",
    "name": "Bolu Marble Ube",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Bolu Marble Ube lezat khas Kopi Kenangan.",
    "price": 11000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_107",
    "brand_id": "brand_kopi_kenangan",
    "name": "Bolu Marble Mocha",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Bolu Marble Mocha lezat khas Kopi Kenangan.",
    "price": 11000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_108",
    "brand_id": "brand_kopi_kenangan",
    "name": "Roti Gulung Abon",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Roti Gulung Abon lezat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_109",
    "brand_id": "brand_kopi_kenangan",
    "name": "Roti Gulung Aren",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Roti Gulung Aren lezat khas Kopi Kenangan.",
    "price": 11000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_110",
    "brand_id": "brand_kopi_kenangan",
    "name": "Canele Original",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Canele Original lezat khas Kopi Kenangan.",
    "price": 10500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_111",
    "brand_id": "brand_kopi_kenangan",
    "name": "Canele Toffee Nut",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Canele Toffee Nut lezat khas Kopi Kenangan.",
    "price": 11500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_112",
    "brand_id": "brand_kopi_kenangan",
    "name": "Butter Croissant",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Butter Croissant lezat khas Kopi Kenangan.",
    "price": 11500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_113",
    "brand_id": "brand_kopi_kenangan",
    "name": "Chocolate Croissant",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Chocolate Croissant lezat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_114",
    "brand_id": "brand_kopi_kenangan",
    "name": "Sandwich Smoked Beef",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Sandwich Smoked Beef lezat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_115",
    "brand_id": "brand_kopi_kenangan",
    "name": "Sandwich Chicken Tartare",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Sandwich Chicken Tartare lezat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_116",
    "brand_id": "brand_kopi_kenangan",
    "name": "Sugar Donut",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Sugar Donut lezat khas Kopi Kenangan.",
    "price": 9000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_117",
    "brand_id": "brand_kopi_kenangan",
    "name": "Roti Coklat Klasik",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Roti Coklat Klasik lezat khas Kopi Kenangan.",
    "price": 8500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_118",
    "brand_id": "brand_kopi_kenangan",
    "name": "Roti Sisir Keju",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Roti Sisir Keju lezat khas Kopi Kenangan.",
    "price": 11000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_119",
    "brand_id": "brand_kopi_kenangan",
    "name": "Roti Sisir Coklat",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Roti Sisir Coklat lezat khas Kopi Kenangan.",
    "price": 10500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_120",
    "brand_id": "brand_kopi_kenangan",
    "name": "Roti Susu Manis",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Roti Susu Manis lezat khas Kopi Kenangan.",
    "price": 8500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_121",
    "brand_id": "brand_kopi_kenangan",
    "name": "Roti Srikaya",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Roti Srikaya lezat khas Kopi Kenangan.",
    "price": 11500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_122",
    "brand_id": "brand_kopi_kenangan",
    "name": "Bambang Choco Cheese",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Bambang Choco Cheese lezat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_123",
    "brand_id": "brand_kopi_kenangan",
    "name": "Adam Ayam Toast",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Adam Ayam Toast lezat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_124",
    "brand_id": "brand_kopi_kenangan",
    "name": "Danish Tiramisu",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Danish Tiramisu lezat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_125",
    "brand_id": "brand_kopi_kenangan",
    "name": "Salt Bread Original",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Salt Bread Original lezat khas Kopi Kenangan.",
    "price": 9500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_126",
    "brand_id": "brand_kopi_kenangan",
    "name": "Wahyu Sapi Toast",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Wahyu Sapi Toast lezat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_127",
    "brand_id": "brand_kopi_kenangan",
    "name": "Donut Tiramisu",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Donut Tiramisu lezat khas Kopi Kenangan.",
    "price": 10500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_128",
    "brand_id": "brand_kopi_kenangan",
    "name": "Dirty Croissant Milo",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Dirty Croissant Milo lezat khas Kopi Kenangan.",
    "price": 13500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_129",
    "brand_id": "brand_kopi_kenangan",
    "name": "Choco Chip Cookies",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Choco Chip Cookies lezat khas Kopi Kenangan.",
    "price": 11000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_130",
    "brand_id": "brand_kopi_kenangan",
    "name": "Friend Chip Cookie",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Friend Chip Cookie lezat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_131",
    "brand_id": "brand_kopi_kenangan",
    "name": "Join the Dark Side Cookie",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Join the Dark Side Cookie lezat khas Kopi Kenangan.",
    "price": 14500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_132",
    "brand_id": "brand_kopi_kenangan",
    "name": "Vanilla Choux Puff",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Vanilla Choux Puff lezat khas Kopi Kenangan.",
    "price": 10000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_133",
    "brand_id": "brand_kopi_kenangan",
    "name": "Strawberry Choux Puff",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Strawberry Choux Puff lezat khas Kopi Kenangan.",
    "price": 10000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_134",
    "brand_id": "brand_kopi_kenangan",
    "name": "Chocolate Choux Puff",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Chocolate Choux Puff lezat khas Kopi Kenangan.",
    "price": 10000,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_135",
    "brand_id": "brand_kopi_kenangan",
    "name": "Choco Mocha Swirl Toast",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Choco Mocha Swirl Toast lezat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_136",
    "brand_id": "brand_kopi_kenangan",
    "name": "Canele Aren",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Canele Aren lezat khas Kopi Kenangan.",
    "price": 11500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_137",
    "brand_id": "brand_kopi_kenangan",
    "name": "Aren Apple Pie",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Aren Apple Pie lezat khas Kopi Kenangan.",
    "price": 12500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_138",
    "brand_id": "brand_kopi_kenangan",
    "name": "Choco Muffin",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Choco Muffin lezat khas Kopi Kenangan.",
    "price": 11500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  },
  {
    "id": "kk_prod_139",
    "brand_id": "brand_kopi_kenangan",
    "name": "Blueberry Muffin",
    "image": "https://i.ibb.co.com/LdNYD0sW/Frame-1410112879.png",
    "description": "Blueberry Muffin lezat khas Kopi Kenangan.",
    "price": 11500,
    "category": "Food",
    "availability": "ON",
    "customization_json": "{}",
    "is_single_item": 0
  }
];
